### ISSUE TITLE
添加rultor的支持

### ISSUE THREAD

**Issue by jcai** [ganshane/monad#51]
添加rultor的支持

**Comment by jcai** [comment]
@rultor 
release tag is `5.0.3` branch is `develop`

**Comment by jcai** [comment]
@yegor256

I can't read log!

**Comment by yegor256** [comment]
@jcai should be fine now

**Comment by jcai** [comment]
@rultor 
please release, tag is `5.0.3`

**Comment by jcai** [comment]
@rultor 
please release, tag is `5.0.3`

**Comment by jcai** [comment]
@yegor256  how to disable default script "mvn clean test" ?

**Comment by yegor256** [comment]
@jcai the problem is that rultor is always looking into `master` branch, while you're keeping your files in `develop` branch. this is probably worth a ticket to Rultor. it has to understand what is the default branch in the repo. in the mean time, update `.rultor.yml` in `master` branch

**Comment by jcai** [comment]
@rultor 
please release, tag is `5.0.3`

**Comment by jcai** [comment]
@yegor256 thank you very much!

**Comment by jcai** [comment]
@rultor 
please release, tag is `5.0.3`

**Comment by jcai** [comment]
@rultor 
please release, tag is `5.0.3.1`

**Comment by jcai** [comment]
> @rultor 
>  please release, tag is `5.0.3.2`

**Comment by jcai** [comment]
@rultor 
 please release, tag is `5.0.3.2`
